apiVersion: apps/v1
kind: Deployment

metadata:
  name: python-app
  namespace: registration

spec:
  replicas: 1

  selector:
    matchLabels:
      app: python-app

  template:
    metadata:
      labels:
        app: python-app

    spec:

      # --------------------------------
      # INIT CONTAINER
      # --------------------------------
      initContainers:

        - name: wait-for-mysql

          image: mysql:8.4

          command:
            - sh
            - -c
            - |
              echo "Waiting for MySQL..."

              until mysqladmin ping \
                -h mysql \
                -uappuser \
                -papppassword \
                --silent
              do
                echo "MySQL is not ready..."
                sleep 5
              done

              echo "MySQL is ready!"

      # --------------------------------
      # PYTHON APPLICATION CONTAINER
      # --------------------------------
      containers:

        - name: python-app

          image: python-registration:2.0

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5000

          env:

            - name: DB_HOST
              value: mysql

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE
