apiVersion: v1
kind: Secret

metadata:
  name: mysql-secret
  namespace: registration

type: Opaque

stringData:

  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_DATABASE: registration
  MYSQL_USER: appuser
  MYSQL_PASSWORD: apppassword
