apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "python-registration.fullname" . }}-mysql

  labels:
    {{- include "python-registration.labels" . | nindent 4 }}
    app: mysql

spec:

  replicas: 1

  selector:
    matchLabels:
      app: mysql
      release: {{ .Release.Name }}

  template:

    metadata:
      labels:
        app: mysql
        release: {{ .Release.Name }}

    spec:

      containers:

        - name: mysql

          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"

          imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}

          ports:

            - name: mysql
              containerPort: {{ .Values.mysql.containerPort }}

          env:

            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "python-registration.fullname" . }}-mysql
                  key: root-password

            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "python-registration.fullname" . }}-mysql
                  key: database

            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "python-registration.fullname" . }}-mysql
                  key: username

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "python-registration.fullname" . }}-mysql
                  key: password

          volumeMounts:

            - name: mysql-storage
              mountPath: /var/lib/mysql

          resources:
            {{- toYaml .Values.mysql.resources | nindent 12 }}

      volumes:

        - name: mysql-storage

          persistentVolumeClaim:
            claimName: {{ include "python-registration.fullname" . }}-mysql-pvc
