apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: {{ .Values.pythonApp.replicaCount }}

  selector:
    matchLabels:
      app: python-app

  template:
    metadata:
      labels:
        app: python-app

    spec:
      containers:
        - name: python-app
          image: "{{ .Values.pythonApp.image.repository }}:{{ .Values.pythonApp.image.tag }}"
          imagePullPolicy: {{ .Values.pythonApp.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.pythonApp.containerPort }}
