apiVersion: v1
kind: Service
metadata:
  name: python-app
  labels:
    {{- include "python-registration.labels" . | nindent 4 }}
spec:
  type: {{ .Values.pythonApp.service.type }}
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: {{ .Values.pythonApp.service.port }}
      targetPort: {{ .Values.pythonApp.service.targetPort }}
