pythonApp:
  replicaCount: 2

  image:
    repository: "208357522135.dkr.ecr.us-east-1.amazonaws.com/python-registration"
    tag: "stage"

  service:
    type: LoadBalancer

mysql:
  persistence:
    enabled: true
    storageClass: gp3
    size: 10Gi
