{{- if .Values.mysql.persistence.enabled }}

apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: {{ include "python-registration.fullname" . }}-mysql-pvc

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: {{ .Values.mysql.persistence.storageClass }}

  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size }}

{{- end }}
