apiVersion: v1
kind: Service

metadata:
  name: {{ include "python-registration.fullname" . }}-mysql

  labels:
    {{- include "python-registration.labels" . | nindent 4 }}

spec:

  type: ClusterIP

  selector:
    app: mysql
    release: {{ .Release.Name }}

  ports:

    - name: mysql
      port: {{ .Values.mysql.service.port }}
      targetPort: {{ .Values.mysql.containerPort }}
      protocol: TCP
